name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Set Gradle properties
      run: |
        echo "mc_version=1.12.2" >> gradle.properties
        echo "forge_version=14.23.5.2860" >> gradle.properties
        echo "mappings=snapshot_20171003" >> gradle.properties
        echo "jei_version=4.16.1.302" >> gradle.properties
        cat gradle.properties
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build jar --stacktrace
      
    - name: Verify build outputs
      run: ls -lh build/libs
      
    - name: Upload mod artifact
      uses: actions/upload-artifact@v4
      with:
        name: mod-artifact
        path: build/libs/*.jar
        retention-days: 3

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Set Gradle properties
      run: |
        echo "mc_version=1.12.2" >> gradle.properties
        echo "forge_version=14.23.5.2860" >> gradle.properties
        echo "mappings=snapshot_20171003" >> gradle.properties
        echo "jei_version=4.16.1.302" >> gradle.properties
    
    - name: Skip dependency graph
      run: echo "Dependency graph skipped for Gradle 2.14"
