name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Set Gradle properties
      run: |
        echo "mc_version=1.12.2" >> gradle.properties
        echo "forge_version=14.23.5.2860" >> gradle.properties
        echo "mappings=snapshot_20171003" >> gradle.properties
        echo "jei_version=4.16.1.302" >> gradle.properties
        cat gradle.properties
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build --stacktrace

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Set Gradle properties
      run: |
        echo "mc_version=1.12.2" >> gradle.properties
        echo "forge_version=14.23.5.2860" >> gradle.properties
        echo "mappings=snapshot_20171003" >> gradle.properties
        echo "jei_version=4.16.1.302" >> gradle.properties
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
