name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Make gradlew executable
      run: chmod +x gradlew
      
    - name: Set Gradle properties
      run: |
        echo "mc_version=1.12.2" >> gradle.properties
        echo "forge_version=14.23.5.2860" >> gradle.properties
        echo "mappings=snapshot_20171003" >> gradle.properties
        echo "jei_version=4.16.1.302" >> gradle.properties
        cat gradle.properties
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
      
    # 修改构建命令
    - name: Build with Gradle Wrapper
      run: ./gradlew build jar --stacktrace
      
    # 添加调试步骤
    - name: List build outputs
      run: |
        echo "构建输出目录:"
        ls -lR build
        echo "libs 目录:"
        ls -l build/libs
        
    # 上传生成的MOD文件
    - name: Upload mod artifact
      uses: actions/upload-artifact@v3
      with:
        name: mod-artifact
        path: build/libs/*.jar

  # 依赖提交作业保持不变
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Make gradlew executable
      run: chmod +x gradlew
    - name: Set Gradle properties
      run: |
        echo "mc_version=1.12.2" >> gradle.properties
        echo "forge_version=14.23.5.2860" >> gradle.properties
        echo "mappings=snapshot_20171003" >> gradle.properties
        echo "jei_version=4.16.1.302" >> gradle.properties
    
    # 禁用依赖关系图生成
    - name: Skip dependency graph generation
      run: echo "Skipping dependency graph due to Gradle 2.14 incompatibility"
